'use client';
import * as React from 'react';
import { Calendar } from '@/components/ui/calendar';
import { ROOMS } from '@/lib/data';

type Booking = { id: string; roomId: string; room: string; checkIn: string; checkOut: string; nights: number; total: number; status: string };
const dateKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const monthKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;

export function AdminCalendar() {
  const [month, setMonth] = React.useState(() => new Date()); const [roomId, setRoomId] = React.useState(ROOMS[0].id); const [bookings, setBookings] = React.useState<Booking[]>([]); const [selected, setSelected] = React.useState<Booking | null>(null); const [error, setError] = React.useState('');
  React.useEffect(() => { const controller = new AbortController(); setError(''); void fetch(`/api/admin/calendar?month=${monthKey(month)}`, { signal: controller.signal }).then(async (response) => { const data = await response.json() as { ok?: boolean; bookings?: Booking[]; error?: string }; if (!response.ok || !data.ok) throw new Error(data.error || 'Could not load occupancy.'); setBookings(data.bookings ?? []); }).catch((reason) => { if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : 'Could not load occupancy.'); }); return () => controller.abort(); }, [month]);
  const roomBookings = bookings.filter((booking) => booking.roomId === roomId);
  const occupiedDays = roomBookings.flatMap((booking) => { const days: Date[] = []; for (let date = booking.checkIn; date < booking.checkOut;) { days.push(new Date(`${date}T00:00:00`)); const next = new Date(`${date}T00:00:00Z`); next.setUTCDate(next.getUTCDate() + 1); date = next.toISOString().slice(0, 10); } return days; });
  const forDate = (date: Date) => roomBookings.find((booking) => dateKey(date) >= booking.checkIn && dateKey(date) < booking.checkOut);
  async function logout() { await fetch('/api/admin/logout', { method: 'POST' }); window.location.reload(); }
  return <main className="min-h-screen bg-sand-50 px-5 py-12 dark:bg-ocean-900"><div className="mx-auto max-w-5xl"><header className="flex items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-teal-600">Azurea owner</p><h1 className="mt-2 font-display text-4xl font-semibold text-ocean-800 dark:text-white">Occupancy & availability</h1></div><button onClick={() => void logout()} className="rounded-full border border-ocean-200 px-4 py-2 text-sm font-semibold text-ocean-700 dark:border-white/15 dark:text-white">Log out</button></header><section className="mt-8 rounded-3xl bg-white p-6 shadow-luxe dark:bg-ocean-800"><div className="flex flex-wrap gap-2">{ROOMS.map((room) => <button key={room.id} onClick={() => { setRoomId(room.id); setSelected(null); }} className={`rounded-full px-4 py-2 text-sm font-semibold ${room.id === roomId ? 'bg-ocean-600 text-white' : 'bg-sand-50 text-ocean-700 dark:bg-white/10 dark:text-white/80'}`}>{room.name}</button>)}</div><div className="mt-6 grid gap-8 lg:grid-cols-[auto_1fr]"><Calendar mode="single" month={month} onMonthChange={setMonth} onDayClick={(date) => setSelected(forDate(date) ?? null)} modifiers={{ occupied: occupiedDays }} modifiersClassNames={{ occupied: 'bg-teal-300 text-ocean-900 font-bold hover:bg-teal-400 dark:bg-teal-400/35 dark:text-white' }} /><aside className="rounded-2xl bg-sand-50 p-5 dark:bg-ocean-900/60"><h2 className="font-display text-2xl font-semibold text-ocean-800 dark:text-white">Stay summary</h2>{error ? <p className="mt-3 text-sm text-red-600">{error}</p> : selected ? <dl className="mt-4 space-y-3 text-sm"><div><dt className="text-muted-foreground">Room</dt><dd className="font-semibold">{selected.room}</dd></div><div><dt className="text-muted-foreground">Stay</dt><dd>{selected.checkIn} to {selected.checkOut}</dd></div><div><dt className="text-muted-foreground">Nights</dt><dd>{selected.nights}</dd></div><div><dt className="text-muted-foreground">Total</dt><dd>₹{selected.total.toLocaleString('en-IN')}</dd></div><div><dt className="text-muted-foreground">Status</dt><dd className="capitalize">{selected.status}</dd></div></dl> : <p className="mt-3 text-sm text-muted-foreground">Teal dates are occupied. Select one to view the stay summary.</p>}</aside></div></section></div></main>;
}
